### ISSUE TITLE
weekly calendar view not working

### ISSUE THREAD

**Issue by 2bread** [dragonwocky/notion-enhancer#101]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
extensions not working even when turned on in the enhancer core and restarted. the only ones that do work are the emojis.

**screenshots**
none

**platform**
Windows 10

**Comment by dragonwocky** [comment]
which extensions? i need specific screenshots/names of every single one you've tested, otherwise i can't help.

**Comment by 2bread** [comment]
hi sorry
all the themes have this same result and do not apply at all

![Capture2](https://user-images.githubusercontent.com/71205060/93011540-58389400-f5da-11ea-93af-bc3f563db131.PNG)

neither does the calendar weekly or properties layouts

![Screenshot 2020-09-13 155453](https://user-images.githubusercontent.com/71205060/93011597-da28bd00-f5da-11ea-8257-ae17b0e56950.png)
![Screenshot 2020-09-13 155745](https://user-images.githubusercontent.com/71205060/93011599-dbf28080-f5da-11ea-9aa0-6a7da1102aad.png)

**Comment by dragonwocky** [comment]
@2bread dark themes will only work if notion is in dark mode. (`ctrl+shift+l` to switch on windows)

**Comment by dragonwocky** [comment]
property layout is already fixed and will be released soon, weekly view i'll look into

**Comment by dragonwocky** [comment]
@2bread did you try reloading notion after enabling weekly view? it's still working when I tested...

**Comment by 2bread** [comment]
i've tried reloading it multiple times with no luck

**Comment by dragonwocky** [comment]
@2bread what platform are you on? have you tested both fullpage and inline?

**Comment by 2bread** [comment]
it's managed to work on fullpage but inline is still an issue and i'm using windows 10

**Comment by dragonwocky** [comment]
alright thanks i'll see what i can do

**Comment by dragonwocky** [comment]
inline, fullpage, and linked views are all alright for me on windows 10.
it may have been accidentally fixed by something else already in the wip build- release will be out soonish, when it is see if you still have this problem.

**Comment by dragonwocky** [comment]
does this still occur in v0.9?

**Comment by 2bread** [comment]
unfortunately it still doesnt work

**Comment by Doeye1997** [comment]
Same problem, but just happen in some page. Others are ok.

**Comment by dragonwocky** [comment]
@Doeye1997 @2bread can you link me to a page where it happens? I still can't replicate this.

**Comment by Doeye1997** [comment]
I find out...
it happens when the calendar under a toggle list, and the toggle list is unfold when you open the page.
once I fold the toggle list it works ok.

**Comment by Doeye1997** [comment]
![image](https://user-images.githubusercontent.com/40802787/93731077-09a08080-fbfe-11ea-82b7-f0d3509bb707.png)
![image](https://user-images.githubusercontent.com/40802787/93731085-1329e880-fbfe-11ea-9781-040a00f3fcf0.png)

**Comment by 2bread** [comment]
I figured out that the issue seems to only occur when linking to a full page calendar. It worked when I linked to an inline instead

**Comment by dragonwocky** [comment]
ah! got it. whenever there was another db view above the weekly calendar it would get stuck on that.
